#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"

export PATH=$HERE/usr/bin:$PATH
export LD_LIBRARY_PATH=$HERE/usr/lib:$LD_LIBRARY_PATH
export QT_PLUGIN_PATH=$HERE/usr/plugins

# TODO: Install script

if [ ! -z $APPIMAGE ]; then
  BINARY_NAME=$(basename "$ARGV0")
  if [ -e "$HERE/usr/bin/$BINARY_NAME" ]; then
    exec "$HERE/usr/bin/$BINARY_NAME" "$@"
  else
    exec "$HERE/usr/bin/MiniZincIDE" "$@"
  fi
else
  exec "$HERE/usr/bin/MiniZincIDE" "$@"
fi