name: minizinc
version: git
summary: The MiniZinc bundle
icon: resources/icon.png
description: |
  MiniZinc is a free and open-source constraint modeling language. You can
  use MiniZinc to model constraint satisfaction and optimization problems in
  a high-level, solver-independent way, taking advantage of a large library
  of pre-defined constraints. Your model is then compiled into FlatZinc, a
  solver input language that is understood by a wide range of solvers.

confinement: classic
base: core18

apps:
  minizinc:
    command: bin/minizinc
  ide:
    command: desktop-launch $SNAP/bin/MiniZincIDE
    desktop: share/applications/MiniZincIDE.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/opt/qt512/lib:$LD_LIBRARY_PATH
      # Use GTK3 cursor theme, icon theme and open/save file dialogs.
      QT_QPA_PLATFORMTHEME: gtk3
      QT_PLUGIN_PATH: $SNAP/opt/qt512/plugins/
      QTDIR: $SNAP/opt/qt512
      # See https://github.com/ubuntu/snapcraft-desktop-helpers/blob/92150d5b3031160998d47c438383d5cc7decf967/qt/launcher-specific#L60
      QTWEBENGINEPROCESS_PATH: $SNAP/opt/qt512/libexec/QtWebEngineProcess

parts:
  ide:
    plugin: nil # Using the qmake plugin will install qt5-qmake which we don't want/need
    source: .
    source-subdir: MiniZincIDE
    after: [desktop-gtk3]
    build-environment:
      - QT_BASE_DIR: /opt/qt512
      - QTDIR: $QT_BASE_DIR
      - PATH: $QTDIR/bin:$PATH
      - LD_LIBRARY_PATH: $QTDIR/lib:$LD_LIBRARY_PATH
      - PKG_CONFIG_PATH: $QTDIR/lib/pkgconfig:$PKG_CONFIG_PATH
    build-packages:
      - build-essential
      # From https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.12.10-bionic
      - qt512base
      - qt512webengine
    stage-packages:
      - qt512base
      - qt512webengine
      # Needed for the web engine
      - libavformat57
      - libdouble-conversion1
      - libevent-2.1-6
      - libminizip1
      - libpulse0
      - libre2-4
      - libxtst6
    override-build: |
      qmake -makefile "CONFIG+=bundled" "DEFINES+=MINIZINC_IDE_BUILD=\\\\\\\"\"${CI_PIPELINE_ID}\\\\\\\"\"" MiniZincIDE.pro
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make INSTALL_ROOT="${SNAPCRAFT_PART_INSTALL}" install
      echo "[Paths]\nPrefix = ../opt/qt512/" > ${SNAPCRAFT_PART_INSTALL}/bin/qt.conf
      echo "[Paths]\nPrefix = ../" > ${SNAPCRAFT_PART_INSTALL}/opt/qt512/libexec/qt.conf
  minizinc:
    plugin: dump
    source: minizinc/
    stage: [bin/, share/]
  vendor:
    plugin: dump
    source: vendor/
    organize:
      gecode/bin/fzn-gecode: bin/
      gecode_gist/bin/fzn-gecode: bin/fzn-gecode-gist
      gecode/share/gecode/mznlib: share/minizinc/gecode
      chuffed/bin/fzn-chuffed: bin/
      chuffed/share/minizinc/*: share/minizinc/
    stage: [bin/, share/minizinc/]
  globalizer:
    plugin: dump
    source: globalizer/
    organize:
      share/globalizer/mznlib: share/minizinc/globalizer
    stage: [bin/, share/minizinc/]
  findmus:
    plugin: dump
    source: findMUS/
    stage: [bin/]
  resources:
    plugin: dump
    source: resources/
    organize:
      scripts/run-fzn-gecode-gist: bin/
      solvers/*.msc: share/minizinc/solvers/
      misc/MiniZincIDE.desktop: share/applications/
    stage: [bin/, share/]
  # This part installs the gtk dependencies and a `desktop-launch` script to initialise
  # desktop-specific features such as fonts, themes and the XDG environment.
  # 
  # It is copied straight from the snapcraft desktop helpers project. Please periodically
  # check the source for updates and copy the changes.
  #    https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  # 
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3
